title: Adam Laycock
description: EdTech Network Manager & Developer

plugins:
  - jekyll-postcss-v2

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - docker-compose.yml
  - package.json
  - package-lock.json
  - tailwind.config.js
  - postcss.config.js
  - LICENSE
  - docker
  - support files

permalink: /:year/:month/:title

collections:
  - cv

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      ogimage: "https://alaycock.co.uk/assets/og-image.png"
  
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"